# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - CostcoChatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Notebooks/Lakshit/GeminiChatbot/requirements.txt

      - name: Zip the application
        run: |
          cd Notebooks/Lakshit/GeminiChatbot
          zip -r release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: Notebooks/Lakshit/GeminiChatbot/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment: Production

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip for deployment
        run: unzip release.zip -d app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_590037C4C9114DC285AD0C37D741D485 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7BDC0C480B05484CA4737CC788B30A53 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_32DD4F1495C1423F936B5535D6EC7AB2 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'CostcoChatbot'
          slot-name: 'Production'
          package: app